import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bd_models", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BattleConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(default="default", help_text="Internal identifier for this configuration profile.", max_length=64, unique=True, verbose_name="configuration name")),
                ("is_active", models.BooleanField(default=True, help_text="Whether this configuration profile is currently in use.", verbose_name="active")),
                ("attack_multiplier", models.FloatField(default=1.0, help_text="Multiplier applied to attacker's Attack stat in the damage formula.", verbose_name="attack multiplier")),
                ("defense_multiplier", models.FloatField(default=1.0, help_text="Multiplier applied to defender's Defense stat in the damage formula.", verbose_name="defense multiplier")),
                ("minimum_damage", models.PositiveIntegerField(default=5, help_text="Damage floor applied after all reductions.", verbose_name="minimum damage")),
                ("critical_hit_chance", models.FloatField(default=0.1, help_text="Probability (0-1) that an attack lands as a critical hit.", verbose_name="critical hit chance")),
                ("critical_hit_multiplier", models.FloatField(default=1.5, help_text="Damage multiplier applied on a critical hit.", verbose_name="critical hit multiplier")),
                ("defend_damage_reduction", models.FloatField(default=0.5, help_text="Fraction of incoming damage negated while defending.", verbose_name="defend damage reduction")),
                ("counter_cooldown_turns", models.PositiveIntegerField(default=2, help_text="Turns a player must wait before using Counter again.", verbose_name="counter cooldown (turns)")),
                ("counter_reflect_multiplier", models.FloatField(default=1.0, help_text="Fraction of negated attack damage reflected back to the attacker.", verbose_name="counter reflect multiplier")),
                ("dodge_cooldown_turns", models.PositiveIntegerField(default=2, help_text="Turns a player must wait before using Dodge again.", verbose_name="dodge cooldown (turns)")),
                ("heal_uses_per_battle", models.PositiveIntegerField(default=3, help_text="Maximum number of times a player may Heal in a single battle.", verbose_name="heal uses per battle")),
                ("heal_amount_fraction", models.FloatField(default=0.25, help_text="Fraction of max HP restored by a single Heal action.", verbose_name="heal amount (fraction of max HP)")),
                ("momentum_max", models.IntegerField(default=5, help_text="Upper bound of the momentum meter.", verbose_name="momentum maximum")),
                ("momentum_min", models.IntegerField(default=-5, help_text="Lower bound of the momentum meter.", verbose_name="momentum minimum")),
                ("momentum_high_threshold", models.IntegerField(default=3, help_text="Momentum value at which the positive damage bonus applies.", verbose_name="momentum high threshold")),
                ("momentum_high_damage_bonus", models.FloatField(default=0.1, help_text="Damage bonus fraction applied at or above the high momentum threshold.", verbose_name="momentum high damage bonus")),
                ("momentum_crit_threshold", models.IntegerField(default=5, help_text="Momentum value at which the critical chance bonus applies.", verbose_name="momentum critical threshold")),
                ("momentum_crit_bonus", models.FloatField(default=0.2, help_text="Bonus fraction added to critical hit chance at the momentum crit threshold.", verbose_name="momentum critical bonus")),
                ("momentum_low_threshold", models.IntegerField(default=-3, help_text="Momentum value at or below which the negative damage penalty applies.", verbose_name="momentum low threshold")),
                ("momentum_low_damage_penalty", models.FloatField(default=0.1, help_text="Damage penalty fraction applied at or below the low momentum threshold.", verbose_name="momentum low damage penalty")),
                ("afk_momentum_penalty", models.IntegerField(default=1, help_text="Momentum lost when a player fails to act before the turn timer expires.", verbose_name="AFK momentum penalty")),
                ("updated_at", models.DateTimeField(blank=True, help_text="Timestamp this configuration was last saved.", null=True, verbose_name="updated at")),
            ],
            options={"verbose_name": "battle configuration", "verbose_name_plural": "battle configurations"},
        ),
        migrations.CreateModel(
            name="BattleMode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Display name shown in the mode selector (e.g. 'Duel', 'Chaos Arena').", max_length=64, unique=True, verbose_name="name")),
                ("description", models.TextField(blank=True, default="", help_text="Player-facing description of this mode.", verbose_name="description")),
                ("icon", models.CharField(blank=True, default="⚔️", help_text="Emoji or short icon token shown next to the mode name.", max_length=100, verbose_name="icon")),
                ("is_enabled", models.BooleanField(default=True, help_text="Whether this mode currently appears in the mode selector.", verbose_name="enabled")),
                ("is_builtin", models.BooleanField(default=False, help_text="Marks Duel / Free For All / Team Battle. Built-in modes can still be fully edited from the dashboard, just not deleted.", verbose_name="built-in")),
                ("mode_type", models.CharField(choices=[("duel", "Duel"), ("ffa", "Free For All"), ("team", "Team Battle")], default="duel", help_text="Underlying pairing rules the engine uses: head-to-head, every-participant-for-themselves, or team-based.", max_length=8, verbose_name="mode type")),
                ("min_players", models.PositiveIntegerField(default=2, help_text="Minimum number of players required to start.", verbose_name="minimum players")),
                ("max_players", models.PositiveIntegerField(default=2, help_text="Maximum number of players allowed to join.", verbose_name="maximum players")),
                ("teams_enabled", models.BooleanField(default=False, help_text="Whether players are split into teams.", verbose_name="teams enabled")),
                ("team_size", models.PositiveIntegerField(default=1, help_text="Players per team, when teams are enabled.", verbose_name="team size")),
                ("allow_spectators", models.BooleanField(default=True, help_text="Whether non-participants may spectate the battle.", verbose_name="allow spectators")),
                ("is_public", models.BooleanField(default=True, help_text="Public lobbies can be joined by anyone; private lobbies are invite-only.", verbose_name="public")),
                ("min_deck_size", models.PositiveIntegerField(default=1, help_text="Minimum number of balls a player must field.", verbose_name="minimum deck size")),
                ("max_deck_size", models.PositiveIntegerField(default=1, help_text="Maximum number of balls a player may field.", verbose_name="maximum deck size")),
                ("allow_duplicate_balls", models.BooleanField(default=True, help_text="Whether a player may field multiple balls of the same species.", verbose_name="allow duplicate balls")),
                ("allowed_rarities", models.JSONField(blank=True, default=list, help_text="Rarity values permitted in this mode. Empty means unrestricted.", verbose_name="allowed rarities")),
                ("blocked_rarities", models.JSONField(blank=True, default=list, help_text="Rarity values explicitly forbidden in this mode.", verbose_name="blocked rarities")),
                ("turn_timer_seconds", models.PositiveIntegerField(default=15, help_text="Seconds each player has to choose an action on their turn.", verbose_name="turn timer (seconds)")),
                ("max_turns", models.PositiveIntegerField(default=30, help_text="Maximum number of turns before the battle is forced to a draw.", verbose_name="maximum turns")),
                ("battle_expiration_seconds", models.PositiveIntegerField(default=300, help_text="Seconds of total inactivity before an unfinished battle expires.", verbose_name="battle expiration (seconds)")),
                ("timeout_behavior", models.CharField(choices=[("auto_defend", "Auto Defend"), ("skip_turn", "Skip Turn"), ("random_action", "Random Action")], default="auto_defend", help_text="What happens to a player who doesn't act before the turn timer runs out.", max_length=16, verbose_name="timeout behaviour")),
                ("enabled_actions", models.JSONField(blank=True, default=list, help_text="Action keys enabled in this mode (attack, defend, counter, heal, dodge, ability). Empty means all enabled.", verbose_name="enabled actions")),
                ("win_multiplier", models.FloatField(default=1.0, help_text="Multiplier applied to the base win reward.", verbose_name="win multiplier")),
                ("loss_multiplier", models.FloatField(default=1.0, help_text="Multiplier applied to the base loss reward.", verbose_name="loss multiplier")),
                ("draw_multiplier", models.FloatField(default=1.0, help_text="Multiplier applied to the base draw reward.", verbose_name="draw multiplier")),
                ("streak_multiplier", models.FloatField(default=1.0, help_text="Multiplier applied to the base win-streak bonus.", verbose_name="streak multiplier")),
                ("allow_surrender", models.BooleanField(default=True, help_text="Whether players may forfeit mid-battle.", verbose_name="allow surrender")),
                ("allow_rematch", models.BooleanField(default=True, help_text="Whether a rematch may be started from the result screen.", verbose_name="allow rematch")),
                ("created_at", models.DateTimeField(blank=True, help_text="Timestamp this mode was created.", null=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(blank=True, help_text="Timestamp this mode was last modified.", null=True, verbose_name="updated at")),
                ("allowed_balls", models.ManyToManyField(blank=True, help_text="If set, only these ball species may be fielded in this mode.", related_name="battle_modes_allowed", to="bd_models.ball", verbose_name="allowed balls")),
                ("banned_balls", models.ManyToManyField(blank=True, help_text="Ball species forbidden in this mode.", related_name="battle_modes_banned", to="bd_models.ball", verbose_name="banned balls")),
            ],
            options={"verbose_name": "battle mode", "verbose_name_plural": "battle modes", "ordering": ["-is_builtin", "name"]},
        ),
        migrations.CreateModel(
            name="BattleReward",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(default="default", help_text="Internal identifier for this reward profile.", max_length=64, unique=True, verbose_name="reward profile name")),
                ("is_active", models.BooleanField(default=True, help_text="Whether this reward profile is currently in use.", verbose_name="active")),
                ("win_reward", models.PositiveIntegerField(default=50, help_text="Base currency awarded to the winner.", verbose_name="win reward")),
                ("loss_reward", models.PositiveIntegerField(default=5, help_text="Base currency awarded to the loser.", verbose_name="loss reward")),
                ("draw_reward", models.PositiveIntegerField(default=15, help_text="Base currency awarded to each player on a draw.", verbose_name="draw reward")),
                ("win_streak_bonus", models.PositiveIntegerField(default=10, help_text="Base extra currency per consecutive win beyond the streak threshold.", verbose_name="win streak bonus")),
                ("win_streak_threshold", models.PositiveIntegerField(default=3, help_text="Minimum consecutive wins required before streak bonuses apply.", verbose_name="win streak threshold")),
            ],
            options={"verbose_name": "battle reward profile", "verbose_name_plural": "battle reward profiles"},
        ),
        migrations.CreateModel(
            name="Ability",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Display name shown in battle embeds.", max_length=100, unique=True, verbose_name="name")),
                ("description", models.TextField(help_text="Player-facing description of what the ability does.", verbose_name="description")),
                ("icon", models.CharField(blank=True, default="✨", help_text="Emoji or short icon token.", max_length=100, verbose_name="icon")),
                ("trigger_type", models.CharField(choices=[("active", "Active (used via the Ability button)"), ("passive", "Passive (triggers automatically on hooks)")], default="active", help_text="Whether this ability is manually activated or triggers automatically on battle hooks.", max_length=8, verbose_name="trigger type")),
                ("cooldown_turns", models.PositiveIntegerField(default=3, help_text="Turns before this ability can trigger again.", verbose_name="cooldown (turns)")),
                ("uses_per_battle", models.PositiveIntegerField(default=1, help_text="Maximum triggers per battle.", verbose_name="uses per battle")),
                ("allowed_rarities", models.JSONField(blank=True, default=list, help_text="Rarity values permitted. Empty means unrestricted.", verbose_name="allowed rarities")),
                ("script", models.TextField(blank=True, default="", help_text="Python ability logic, run through the sandboxed Ability API. See the in-dashboard editor for available hooks and helpers.", verbose_name="ability script")),
                ("settings", models.JSONField(blank=True, default=dict, help_text="Free-form settings passed to the script as `ctx.settings`.", verbose_name="settings")),
                ("is_enabled", models.BooleanField(default=True, help_text="Whether this ability is currently usable.", verbose_name="enabled")),
                ("created_at", models.DateTimeField(blank=True, help_text="Timestamp this ability was created.", null=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(blank=True, help_text="Timestamp this ability was last modified.", null=True, verbose_name="updated at")),
                ("allowed_balls", models.ManyToManyField(blank=True, help_text="Ball species that may use this ability. Empty means unrestricted by species.", related_name="battle_abilities", to="bd_models.ball", verbose_name="allowed balls")),
                ("allowed_regimes", models.ManyToManyField(blank=True, help_text="Regimes permitted to use this ability. Empty means unrestricted.", related_name="battle_abilities", to="bd_models.regime", verbose_name="allowed regimes")),
                ("allowed_economies", models.ManyToManyField(blank=True, help_text="Economies permitted to use this ability. Empty means unrestricted.", related_name="battle_abilities", to="bd_models.economy", verbose_name="allowed economies")),
                ("allowed_modes", models.ManyToManyField(blank=True, help_text="Battle modes this ability may be used in. Empty means unrestricted.", related_name="allowed_abilities", to="battles.battlemode", verbose_name="allowed modes")),
            ],
            options={"verbose_name": "ability", "verbose_name_plural": "abilities"},
        ),
        migrations.CreateModel(
            name="Battle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("guild_id", models.BigIntegerField(help_text="Discord guild ID the battle was started in.", verbose_name="guild ID")),
                ("channel_id", models.BigIntegerField(help_text="Discord channel ID the battle message lives in.", verbose_name="channel ID")),
                ("message_id", models.BigIntegerField(blank=True, help_text="Discord message ID of the live battle embed.", null=True, verbose_name="message ID")),
                ("status", models.CharField(choices=[("lobby", "Lobby"), ("active", "Active"), ("finished", "Finished"), ("expired", "Expired"), ("cancelled", "Cancelled")], default="lobby", help_text="Current lifecycle state.", max_length=16, verbose_name="status")),
                ("current_turn", models.PositiveIntegerField(default=0, help_text="Index of the current turn, starting at 0.", verbose_name="current turn")),
                ("winner_team", models.IntegerField(blank=True, help_text="The winning team number, for Team Battle outcomes.", null=True, verbose_name="winner team")),
                ("state", models.JSONField(blank=True, default=dict, help_text="Free-form engine state: active status effects, per-ability trigger counts, misc bookkeeping.", verbose_name="engine state")),
                ("config_snapshot", models.JSONField(blank=True, default=dict, help_text="Snapshot of BattleMode + BattleConfig values in effect when this battle started.", verbose_name="config snapshot")),
                ("created_at", models.DateTimeField(blank=True, help_text="Timestamp the battle was created.", null=True, verbose_name="created at")),
                ("last_action_at", models.DateTimeField(blank=True, help_text="Timestamp of the most recent player action.", null=True, verbose_name="last action at")),
                ("finished_at", models.DateTimeField(blank=True, help_text="Timestamp the battle concluded.", null=True, verbose_name="finished at")),
                ("mode", models.ForeignKey(help_text="The mode this battle is being played under.", on_delete=django.db.models.deletion.PROTECT, related_name="battles", to="battles.battlemode", verbose_name="mode")),
            ],
            options={"verbose_name": "battle", "verbose_name_plural": "battles"},
        ),
        migrations.CreateModel(
            name="BattleParticipant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_id", models.BigIntegerField(help_text="Discord user ID of this participant.", verbose_name="user ID")),
                ("team", models.IntegerField(blank=True, help_text="Team number, when the mode has teams enabled.", null=True, verbose_name="team")),
                ("join_order", models.PositiveIntegerField(default=0, help_text="Order this participant joined the lobby, used for turn ordering.", verbose_name="join order")),
                ("hp", models.IntegerField(default=0, help_text="Current HP.", verbose_name="HP")),
                ("max_hp", models.IntegerField(default=0, help_text="Max HP at battle start, snapshotted from the ball's existing stats.", verbose_name="max HP")),
                ("attack", models.IntegerField(default=0, help_text="Attack stat snapshotted at battle start.", verbose_name="attack")),
                ("defense", models.IntegerField(default=0, help_text="Defense stat snapshotted at battle start.", verbose_name="defense")),
                ("speed", models.IntegerField(default=0, help_text="Speed stat snapshotted at battle start.", verbose_name="speed")),
                ("momentum", models.IntegerField(default=0, help_text="Current momentum value.", verbose_name="momentum")),
                ("cooldowns", models.JSONField(blank=True, default=dict, help_text="Action/ability cooldowns keyed by action or ability id.", verbose_name="cooldowns")),
                ("heal_uses", models.PositiveIntegerField(default=0, help_text="Heal uses consumed so far this battle.", verbose_name="heal uses")),
                ("ability_uses", models.JSONField(blank=True, default=dict, help_text="Per-ability use counts this battle, keyed by ability id.", verbose_name="ability uses")),
                ("is_alive", models.BooleanField(default=True, help_text="Whether this participant is still standing.", verbose_name="alive")),
                ("is_spectator", models.BooleanField(default=False, help_text="Joined to watch rather than fight.", verbose_name="spectator")),
                ("surrendered", models.BooleanField(default=False, help_text="Whether this participant forfeited.", verbose_name="surrendered")),
                ("battle", models.ForeignKey(help_text="The battle this seat belongs to.", on_delete=django.db.models.deletion.CASCADE, related_name="participants", to="battles.battle", verbose_name="battle")),
                ("ball_instance", models.ForeignKey(help_text="The ball instance this participant is fielding.", on_delete=django.db.models.deletion.CASCADE, related_name="battle_participations", to="bd_models.ballinstance", verbose_name="ball instance")),
            ],
            options={"verbose_name": "battle participant", "verbose_name_plural": "battle participants", "ordering": ["battle", "join_order"]},
        ),
        migrations.AddField(
            model_name="battle",
            name="winner_participant",
            field=models.ForeignKey(blank=True, help_text="The winning participant, for Duel/FFA outcomes.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="won_battles", to="battles.battleparticipant", verbose_name="winner"),
        ),
        migrations.CreateModel(
            name="BattleTurn",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("turn_number", models.PositiveIntegerField(help_text="Index of this turn within the battle, starting at 0.", verbose_name="turn number")),
                ("actions", models.JSONField(blank=True, default=dict, help_text='Chosen actions keyed by participant id, e.g. {"3": {"action": "attack", "target_id": 4}}.', verbose_name="actions")),
                ("result", models.JSONField(blank=True, default=dict, help_text="Structured resolution details keyed by participant id.", verbose_name="result")),
                ("created_at", models.DateTimeField(blank=True, help_text="Timestamp this turn was resolved.", null=True, verbose_name="created at")),
                ("battle", models.ForeignKey(help_text="The battle this turn belongs to.", on_delete=django.db.models.deletion.CASCADE, related_name="turns", to="battles.battle", verbose_name="battle")),
            ],
            options={"verbose_name": "battle turn", "verbose_name_plural": "battle turns", "ordering": ["battle", "turn_number"]},
        ),
        migrations.AddIndex(model_name="battle", index=models.Index(fields=["status"], name="battles_bat_status_idx")),
        migrations.AddIndex(model_name="battle", index=models.Index(fields=["guild_id", "channel_id"], name="battles_bat_guild_c_idx")),
        migrations.AlterUniqueTogether(name="battleparticipant", unique_together={("battle", "user_id")}),
        migrations.AlterUniqueTogether(name="battleturn", unique_together={("battle", "turn_number")}),
    ]
